server:
  error:
    path: /error
    whitelabel:
      enabled: false
  port: 8081
spring:
  application:
    name: Book-Form
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   generate-ddl : true
   hibernate.ddl-auto : update
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  cloud:
    consul:
      enabled: true 
      host: localhost
      port: 8500
     # discovery:
       # healthCheckPath: /health
       # healthCheckInterval: 15s
       # instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}     
 
#logging:
  #  level:
   #   org.springframework: 'debug '
      
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update